# Generated by Django 2.2 on 2020-07-09 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transistors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, max_length=1500)),
                ('aplications', models.TextField(blank=True, max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_1', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_2', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_3', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_4', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datasheet', models.URLField(blank=True)),
                ('similar_components', models.TextField(blank=True, max_length=1500)),
                ('division', models.CharField(blank=True, choices=[('general', 'GENERAL'), ('bipolar', 'BIPOLAR'), ('jfet', 'JFET'), ('mosfet', 'MOSFET'), ('fototransistor', 'FOTOTRANSISTOR'), ('device', 'DEVICE')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_transistor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Resistors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, max_length=1500)),
                ('aplications', models.TextField(blank=True, max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_1', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_2', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_3', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_4', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datasheet', models.URLField(blank=True)),
                ('division', models.CharField(blank=True, choices=[('general', 'General'), ('termistor', 'Termistor'), ('carbon', 'Carbon'), ('power', 'Power'), ('potenciometer', 'Potenciometer'), ('smd', 'SMD'), ('accuracy', 'Accuracy')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_resistor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Diodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, max_length=1500)),
                ('aplications', models.TextField(blank=True, max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_1', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_2', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_3', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_4', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datasheet', models.URLField(blank=True)),
                ('similar_components', models.TextField(blank=True, max_length=1500)),
                ('division', models.CharField(blank=True, choices=[('general', 'General'), ('l.e.d', 'L.E.D'), ('rectifier', 'Rectifier'), ('zener', 'Zener'), ('shottky', 'Shottky'), ('device', 'Device')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_diode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Capacitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, max_length=1500)),
                ('aplications', models.TextField(blank=True, max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_1', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_2', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_3', models.ImageField(blank=True, upload_to='blog/img')),
                ('image_4', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datasheet', models.URLField(blank=True)),
                ('division', models.CharField(blank=True, choices=[('general', 'General'), ('ceramic', 'Ceramic'), ('electrolitic', 'Electrolitic'), ('variable', 'Variable'), ('smd', 'SMD'), ('tantalio', 'Tantalio'), ('polyester', 'Polyester')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_capacitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
