# Generated by Django 3.0.7 on 2020-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aplications',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='features',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='similar_components',
            field=models.TextField(default=None),
        ),
    ]
