# Generated by Django 3.0.7 on 2020-06-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200611_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aplications',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='post',
            name='features',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='post',
            name='similar_components',
            field=models.TextField(default='Null'),
        ),
    ]
