# Generated by Django 3.0.7 on 2020-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200611_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aplications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='similar_components',
            field=models.TextField(blank=True),
        ),
    ]
