# Generated by Django 3.0.7 on 2020-06-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200611_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aplications',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='features',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='similar_components',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
