# Generated by Django 3.0.7 on 2020-06-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200611_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='component',
            field=models.CharField(blank=True, choices=[('resistor', 'Resistor'), ('capacitor', 'Capacitor'), ('diode', 'Diode'), ('transistor', 'Transistor'), ('fuse', 'Fuse')], max_length=15),
        ),
    ]
