# Generated by Django 3.0.7 on 2020-06-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datasheet',
            field=models.URLField(blank=True),
        ),
    ]
