# Generated by Django 3.0.7 on 2020-06-12 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_post_datasheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='aplications',
        ),
        migrations.RemoveField(
            model_name='post',
            name='component',
        ),
        migrations.RemoveField(
            model_name='post',
            name='datasheet',
        ),
        migrations.RemoveField(
            model_name='post',
            name='features',
        ),
        migrations.RemoveField(
            model_name='post',
            name='similar_components',
        ),
        migrations.CreateModel(
            name='Transistors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, max_length=1500)),
                ('aplications', models.TextField(blank=True, max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datasheet', models.URLField(blank=True)),
                ('similar_components', models.TextField(blank=True, max_length=1500)),
                ('division', models.CharField(blank=True, choices=[('bjt_npn', 'BJT_NPN'), ('btt_pnp', 'BJT_PNP')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_transistor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Resistors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, max_length=1500)),
                ('aplications', models.TextField(blank=True, max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datasheet', models.URLField(blank=True)),
                ('division', models.CharField(blank=True, choices=[('metal_film', 'Metal_Film'), ('power', 'Power'), ('potenciometer', 'Potenciometer'), ('smd', 'SMD'), ('acuraty', 'acuraty')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_resistor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Diodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, max_length=1500)),
                ('aplications', models.TextField(blank=True, max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datasheet', models.URLField(blank=True)),
                ('similar_components', models.TextField(blank=True, max_length=1500)),
                ('division', models.CharField(blank=True, choices=[('l.e.d', 'L.E.D'), ('rectifier', 'Rectifier'), ('zener', 'Zener'), ('smd', 'SMD')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_diode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Capacitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, max_length=1500)),
                ('aplications', models.TextField(blank=True, max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to='blog/img')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datasheet', models.URLField(blank=True)),
                ('division', models.CharField(blank=True, choices=[('ceramic', 'Ceramic'), ('electrolitic', 'Electrolitic'), ('variable', 'Variable'), ('smd', 'SMD'), ('tantalio', 'Tantalio'), ('polyester', 'Polyester')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Daft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_capacitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
