# Generated by Django 2.2 on 2020-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200617_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitors',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='capacitors',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='capacitors',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='capacitors',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='diodes',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='diodes',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='diodes',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='diodes',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='transistors',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='transistors',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='transistors',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AddField(
            model_name='transistors',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='blog/img'),
        ),
        migrations.AlterField(
            model_name='capacitors',
            name='division',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('ceramic', 'Ceramic'), ('electrolitic', 'Electrolitic'), ('variable', 'Variable'), ('smd', 'SMD'), ('tantalio', 'Tantalio'), ('polyester', 'Polyester')], max_length=15),
        ),
        migrations.AlterField(
            model_name='diodes',
            name='division',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('l.e.d', 'L.E.D'), ('rectifier', 'Rectifier'), ('zener', 'Zener'), ('smd', 'SMD')], max_length=15),
        ),
        migrations.AlterField(
            model_name='resistors',
            name='division',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('metal_film', 'Metal_Film'), ('carbon', 'Carbon'), ('power', 'Power'), ('potenciometer', 'Potenciometer'), ('smd', 'SMD'), ('acuraty', 'acuraty')], max_length=15),
        ),
        migrations.AlterField(
            model_name='transistors',
            name='division',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('bjt_npn', 'BJT_NPN'), ('btt_pnp', 'BJT_PNP')], max_length=15),
        ),
    ]
