# Generated by Django 2.2 on 2020-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200617_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resistors',
            name='division',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('termistor', 'Termistor'), ('carbon', 'Carbon'), ('power', 'Power'), ('potenciometer', 'Potenciometer'), ('smd', 'SMD'), ('acuraty', 'acuraty')], max_length=15),
        ),
    ]
