# Generated by Django 2.2 on 2020-06-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200617_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diodes',
            name='division',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('l.e.d', 'L.E.D'), ('rectifier', 'Rectifier'), ('zener', 'Zener'), ('shottky', 'Shottky'), ('device', 'Device')], max_length=15),
        ),
    ]
