# Generated by Django 2.2 on 2020-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200707_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistors',
            name='division',
            field=models.CharField(blank=True, choices=[('general', 'GENERAL'), ('bipolar', 'BIPOLAR'), ('jfet', 'JFET'), ('mosfet', 'MOSFET'), ('fototransistor', 'FOTOTRANSISTOR'), ('device', 'DEVICE')], max_length=15),
        ),
    ]
