# Generated by Django 2.2 on 2020-07-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200708_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transistors',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
